version: '3'

volumes:
  kittygram_pg_data:
  static:
  media:

services:
  kittygram:
    image: postgres:13.10
    env_file: .env
    volumes:
      - kittygram_pg_data:/var/lib/postgresql/data
  backend:
    image: lanarkk/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media
    depends_on:
      - kittygram
  frontend:
    env_file: .env
    image: lanarkk/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: lanarkk/kittygram_gateway
    env_file: .env
    ports:
      - 9000:8080
    volumes:
      - static:/staticfiles
      - media
