version: '3'

volumes:
  pg_data:
  static_volume:
  media:

services:
  db:
      image: postgres:13.10
      env_file: .env
      volumes:
        - pg_data:/var/lib/postgresql/data
  backend:
    image: lanarkk/kittygram_backend 
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media/
    depends_on:
      - db
  frontend:
    env_file: .env
    image: lanarkk/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: lanarkk/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media:/media/
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80